<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Code</name>
   <tag></tag>
   <elementGuidId>1bf5c782-042b-4bec-83ba-e574a2a03f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='scroll']/div/div[2]/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body > a.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.card-body > .btn >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ff4b282-e0bd-4510-931b-b2a5382bddbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ef012e9d-b5c8-4d2c-afee-e7f629f7cd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7a2b883c-786f-41df-9942-994f8f32a34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://github.com/HuzefaAbbasi/smartInvest</value>
      <webElementGuid>d86de155-bc91-4b0f-9a1e-9b34e6d244a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a98f2e24-6a3a-4ea2-982d-60594d392e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>39f3a7c2-ca80-45fd-81da-942f9c961713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Code</value>
      <webElementGuid>c32bec91-5465-4b03-9acc-8efbb60f121e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scroll&quot;)/div[@class=&quot;project-section container-fluid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;project-card col-md-4&quot;]/div[@class=&quot;project-card-view card&quot;]/div[@class=&quot;card-body&quot;]/a[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>631acb1c-5091-4888-a80e-8b9fca4547b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scroll']/div/div[2]/div/div/div/div/a</value>
      <webElementGuid>942615e8-3ca6-488c-aa5a-0be95167f2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Code')]</value>
      <webElementGuid>09d5bc59-af2b-45f2-b28d-ecb511b9ed0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Smart Invest'])[1]/following::a[1]</value>
      <webElementGuid>f10ac067-f9c1-44a8-a221-fef7ca173607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Projects'])[1]/following::a[1]</value>
      <webElementGuid>995d3cf1-5719-4071-846f-90d24b1add40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Pool'])[1]/preceding::a[1]</value>
      <webElementGuid>bf37bdea-e6de-4065-b004-1f34661bf730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://github.com/HuzefaAbbasi/smartInvest')]</value>
      <webElementGuid>677bd448-0c0d-4056-bbe7-e17ec70f1ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>2003bdd3-4ffc-4891-a354-d95d3b0fce29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://github.com/HuzefaAbbasi/smartInvest' and (text() = '   Code' or . = '   Code')]</value>
      <webElementGuid>719f13f9-3c3b-4075-81f9-72aace2a4282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
